### ISSUE TITLE
user issue 

### ISSUE THREAD

**Issue by Ujjwal-afk** [Poko-Apps/MemKernel#1]
in user/driver.hpp 

#include
 <cstdint>

for  uintptr_t

**Comment by Poko-Apps** [comment]
Show me the error if possible.

**Comment by Ujjwal-afk** [comment]
here come in telegram i will show @Creampie_001

**Comment by Ujjwal-afk** [comment]
[build_log.txt](https://github.com/user-attachments/files/17509139/build_log.txt)

#include <cstdint>

**Comment by Poko-Apps** [comment]
Include stdint in driver.hpp like this:
```#include <stdint.h>```
And let me know if problem fix or not.
Also about this error :
```
driver.hpp: In member function ‘ssize_t MemKDriver::write(int, const void*, size_t) const’:
driver.hpp:62:79: error: too many initializers for ‘MemKDriver::CopyMemory’
   62 |                 CopyMemory cm = { pid, addr, const_cast<void *>(buffer), size };
```
Use c++ 11 atleast
